spring:
  datasource:
    username: market
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8011